// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRa1LMP73ab89IV6l_peiaJ2PQIvS8UGw',
    appId: '1:250703652175:web:05e974dd4a9958041fd13a',
    messagingSenderId: '250703652175',
    projectId: 'medi-minder-fb28c',
    authDomain: 'medi-minder-fb28c.firebaseapp.com',
    storageBucket: 'medi-minder-fb28c.firebasestorage.app',
    measurementId: 'G-1XRGN2YMVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnpQSmQnP1MM37NyTVVvz8EJSTJetlxFY',
    appId: '1:250703652175:android:f7472cb915438c4a1fd13a',
    messagingSenderId: '250703652175',
    projectId: 'medi-minder-fb28c',
    storageBucket: 'medi-minder-fb28c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnI-dK8uzb9vOQ133W_xHWiOXN0T8M2bo',
    appId: '1:250703652175:ios:ddf23c2842494f2e1fd13a',
    messagingSenderId: '250703652175',
    projectId: 'medi-minder-fb28c',
    storageBucket: 'medi-minder-fb28c.firebasestorage.app',
    iosBundleId: 'com.example.mediminderPillreminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnI-dK8uzb9vOQ133W_xHWiOXN0T8M2bo',
    appId: '1:250703652175:ios:ddf23c2842494f2e1fd13a',
    messagingSenderId: '250703652175',
    projectId: 'medi-minder-fb28c',
    storageBucket: 'medi-minder-fb28c.firebasestorage.app',
    iosBundleId: 'com.example.mediminderPillreminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRa1LMP73ab89IV6l_peiaJ2PQIvS8UGw',
    appId: '1:250703652175:web:614015b738b7e3681fd13a',
    messagingSenderId: '250703652175',
    projectId: 'medi-minder-fb28c',
    authDomain: 'medi-minder-fb28c.firebaseapp.com',
    storageBucket: 'medi-minder-fb28c.firebasestorage.app',
    measurementId: 'G-B22BSGKXT3',
  );

}